name: "Nodejs-Demo CI"
on: push

jobs:
  build:
     runs-on: ubuntu-latest
       
     steps:
       - name: Checkout
         uses: actions/checkout@v3
         
       - name: Setup JFrog CLI
         uses: jfrog/setup-jfrog-cli@v4
         env:  
           JF_URL: ${{ vars.JF_URL }}
           JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
           
       - name: Setup Node npm
         uses: actions/setup-node@v3
           
       - name: Set CLI Config
         run: jf npm-config --global=true --repo-resolve=nodejs-demo-npm --repo-deploy=nodejs-demo-npm
           
       - name: Install Deps
         working-directory: ./src
         run: jf npm install

       - name: Start App
         working-directory: ./src
         run: |
           npm start &
           npx wait-on http://localhost:3000 -t 30000
           
       - name: Run tests
         working-directory: ./src
         run: npm test
         
       - name: Publish
         working-directory: ./src
         run: jf npm publish

       - name: Build Docker Image
         working-directory: ./
         env:
           IMAGE_NAME: joefrog.jfrog.io/nodejs-demo/nodejs-demo-image:${{ github.run_number }}
         run: |
          jf docker build -t $IMAGE_NAME ./build
          jf docker push $IMAGE_NAME
         
       - name: Publish Build info With JFrog CLI
         working-directory: ./src
         run: |
          # Collect environment variables for the build
          jf rt build-collect-env
          # Collect VCS details from git and add them to the build
          jf rt build-add-git
          # Publish build info
          jf rt build-publish
